# cleanup.R — Quarto post-render hook
# Removes yml scaffolding generated by bin/render.
# Skipped when PSHA_KEEP_YML=1 is set in the environment.

if (!identical(Sys.getenv("PSHA_KEEP_YML"), "1")) {
  unlink(c(
    "_quarto.yml",
    "_quarto-book.yml",
    "_quarto-revealjs.yml",
    "_quarto-docx.yml",
    "_quarto-html.yml"
  ))
}
