```{r}
#| include: true
root <- here::here()          
```

:::{.content-hidden when-format='docx'}
:::{.panel-tabset .full-width }


```{r}
#| include: true
#| tbl-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| tbl-cap: !expr CAP  |> sprintf(min(TR_TARGET),max(TR_TARGET),min(Vs30_TARGET),max(Vs30_TARGET),"mean")
p_TARGET <- "mean"
source(file.path(root,"scripts","tbl/AF.R"))
TBL
```
&nbsp;
:::
:::


:::  {  .content-hidden when-format=“docx” }
:::{.panel-tabset .full-width }


#### mean {.unnumbered}

```{r}
#| include: true
#| label: af5
#| tbl-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| tbl-cap: !expr CAP  |> sprintf(min(TR_TARGET),max(TR_TARGET),min(Vs30_TARGET),max(Vs30_TARGET),"mean")
p_TARGET <- "mean"
source(file.path(root,"scripts","tbl/AF.R"))
TBL
```



#### 50% {.unnumbered}

```{r}
#| include: true
#| label: af6
#| tbl-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| tbl-cap: !expr CAP  |> sprintf(min(TR_TARGET),max(TR_TARGET),min(Vs30_TARGET),max(Vs30_TARGET),0.50)
p_TARGET <- 0.50
source(file.path(root,"scripts","tbl/AF.R"))
TBL
```


#### 84% $(+1\ \sigma)$ {.unnumbered}
```{r}
#| include: true
#| label: af7
#| tbl-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| tbl-cap: !expr CAP  |> sprintf(min(TR_TARGET),max(TR_TARGET),min(Vs30_TARGET),max(Vs30_TARGET),0.84)
p_TARGET <- 0.84
source(file.path(root,"scripts","tbl/AF.R"))
TBL

```


#### 90% $(+1.28\ \sigma)$ {.unnumbered}

```{r}
#| include: true
#| label: af8
#| tbl-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| tbl-cap: !expr CAP  |> sprintf(min(TR_TARGET),max(TR_TARGET),min(Vs30_TARGET),max(Vs30_TARGET),0.90)
p_TARGET <- 0.90
source(file.path(root,"scripts","tbl/AF.R"))
TBL

```



#### 95% $(+1.65\ \sigma)$ {.unnumbered}

```{r}
#| include: true
#| label: af9
#| tbl-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| tbl-cap: !expr CAP  |> sprintf(min(TR_TARGET),max(TR_TARGET),min(Vs30_TARGET),max(Vs30_TARGET),0.95)
p_TARGET <- 0.95
source(file.path(root,"scripts","tbl/AF.R"))
TBL
```


:::

:::


```{r}
#| include: false
rm(p_TARGET, Vs30_TARGET, TR_TARGET, CAP)
```
