:::{.content-hidden when-format='html'}
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[5], p_TARGET)
Vs30_TARGET <- Vs30_gmdp[5]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```
:::

:::{.content-hidden when-format='docx'}
:::{.panel-tabset .full-width }

#### `r Site_LABEL[7]`
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[7], p_TARGET)
#| tbl-label: "!expr(sprintf('tbl-psa-%s', as.character(as.numeric(Sys.time()))))"
Vs30_TARGET <- Vs30_gmdp[7]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```

#### `r Site_LABEL[6]`
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[6], p_TARGET)
#| tbl-label: "!expr(sprintf('tbl-psa-%s', as.character(as.numeric(Sys.time()))))"
Vs30_TARGET <- Vs30_gmdp[6]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```

#### `r Site_LABEL[5]`
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[5], p_TARGET)
#| tbl-label: "!expr(sprintf('tbl-psa-%s', as.character(as.numeric(Sys.time()))))"
Vs30_TARGET <- Vs30_gmdp[5]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```

#### `r Site_LABEL[4]`
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[4], p_TARGET)
#| tbl-label: "!expr(sprintf('tbl-psa-%s', as.character(as.numeric(Sys.time()))))"
Vs30_TARGET <- Vs30_gmdp[4]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```

#### `r Site_LABEL[3]`
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[3], p_TARGET)
#| tbl-label: "!expr(sprintf('tbl-psa-%s', as.character(as.numeric(Sys.time()))))"
Vs30_TARGET <- Vs30_gmdp[3]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```

#### `r Site_LABEL[2]`
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[2], p_TARGET)
#| tbl-label: "!expr(sprintf('tbl-psa-%s', as.character(as.numeric(Sys.time()))))"
Vs30_TARGET <- Vs30_gmdp[2]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```

#### `r Site_LABEL[1]`
```{r}
#| include: true
#| tbl-cap: !expr CAP |> sprintf(PSA_Units, min(TR_TARGET), max(TR_TARGET), min(Tn_TARGET), max(Tn_TARGET), Vs30_gmdp[1], p_TARGET)
#| tbl-label: "!expr(sprintf('tbl-psa-%s', as.character(as.numeric(Sys.time()))))"
Vs30_TARGET <- Vs30_gmdp[1]
source(file.path(root, "scripts", "tbl/PSA.R"))
TBL
```

:::
:::

```{r}
#| include: false
rm(Vs30_TARGET)
```
