```{r}
#| include: false
CAP <- "Probability of Exceedance (POE) disaggregated by seismic source for Sa(Tn=%g) [g]. ITo=%g yr. Vs30=%d m/s."
Vs30_TARGET <- 760
if (!exists("ID_TARGET")) ID_TARGET <- ID_gmdp
if (!exists("POE_MIN")) POE_MIN <- 0.50
ITo <- unique(AEPSTable$ITo)[1]

```

:::{.content-visible when-format='docx'}
:::




:::{.content-hidden when-format='docx'}
:::{.panel-tabset .full-width }

### $T_n=0$ (PGA)
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(0, ITo, Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10
 
Tn_TARGET <- 0
source(file.path(root,"scripts","fig/POES.R"))
PLOT
```

### $0.10\,s$
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(0.1, ITo, Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10
 
Tn_TARGET <- 0.1
source(file.path(root,"scripts","fig/POES.R"))
PLOT
```

### $0.20\,s$
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(0.2, ITo, Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10
 
Tn_TARGET <- 0.2
source(file.path(root,"scripts","fig/POES.R"))
PLOT
```

### $0.50\,s$
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(0.5, ITo, Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10
 
Tn_TARGET <- 0.5
source(file.path(root,"scripts","fig/POES.R"))
PLOT
```

### $1.0\,s$
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(1.0, unique(AEPSTable$ITo)[1], Vs30_TARGET)
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10
 
Tn_TARGET <- 1.0
source(file.path(root,"scripts","fig/POES.R"))
PLOT
```

:::
:::

```{r}
#| include: false
rm(ID_TARGET, Vs30_TARGET, Tn_TARGET, POE_MIN, ITo)
```
