
:::{.panel-tabset .full-width }

#### $`r Site_LABEL[7]`$
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(Vs30_gmdp[1], prettyNum(round(TR_TARGET,0), big.mark=","))
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10

Vs30_TARGET <- Vs30_gmdp[7]
source(file.path(root,"scripts","fig/UHS.R"))
PLOT
```

#### `r Site_LABEL[6]`
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(Vs30_gmdp[2], prettyNum(round(TR_TARGET,0), big.mark=","))
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10

Vs30_TARGET <- Vs30_gmdp[6]
source(file.path(root,"scripts","fig/UHS.R"))
PLOT
```

#### `r Site_LABEL[5]`
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(Vs30_gmdp[3], prettyNum(round(TR_TARGET,0), big.mark=","))
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10

Vs30_TARGET <- Vs30_gmdp[5]
source(file.path(root,"scripts","fig/UHS.R"))
PLOT
```

#### `r Site_LABEL[4]`
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(Vs30_gmdp[4], prettyNum(round(TR_TARGET,0), big.mark=","))
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10

Vs30_TARGET <- Vs30_gmdp[4]
source(file.path(root,"scripts","fig/UHS.R"))
PLOT
```

#### `r Site_LABEL[3]`
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(Vs30_gmdp[5], prettyNum(round(TR_TARGET,0), big.mark=","))
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10

Vs30_TARGET <- Vs30_gmdp[3]
source(file.path(root,"scripts","fig/UHS.R"))
PLOT
```

#### `r Site_LABEL[2]`
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(Vs30_gmdp[6], prettyNum(round(TR_TARGET,0), big.mark=","))
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10

Vs30_TARGET <- Vs30_gmdp[2]
source(file.path(root,"scripts","fig/UHS.R"))
PLOT
```

#### `r Site_LABEL[1]`
```{r}
#| include: true
#| fig-cap: !expr CAP |> sprintf(Vs30_gmdp[7], prettyNum(round(TR_TARGET,0), big.mark=","))
#| fig-label: "!expr(sprintf('fig-%s', as.character(as.numeric(Sys.time()))))"
#| column: body-outset
#| out-width: "100%"
#| fig-width: 10

Vs30_TARGET <- Vs30_gmdp[1]
source(file.path(root,"scripts","fig/UHS.R"))
PLOT
```

:::
